# usage: conda env create -p $(pwd)/miniconda/envs/driver-analysis --file environment.yaml 
# -p flag should point to your miniconda installation path.

# name of the conda environment
name: driver-analysis

#the paths that conda takes a look for packages. 
#avoid using anaconda as we have experienced issues with it
channels:
        - jacek_marzec
        - conda-forge
        - bioconda
        - r
        - plotly
        - defaults

#install following packages in the conda environment
dependencies:
        - r-knitr
        - r-rmarkdown
        - r-optparse
        - r-dndscv
        - r-ggplot2
        - r-dt
        - r-upsetr
        - r-stringr
        - r-plotly=4.9.0
        - r-magick
        - r-rcircos
        - r-devtools
        - bioconductor-ensdb.hsapiens.v75
        - bioconductor-ensdb.hsapiens.v86
        - bioconductor-iranges
        - bioconductor-maftools
        - python-dateutil
        - pycurl

